### ISSUE TITLE
Format of moderator events should be more compact

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [magge-faf/faf-moderator-client-develop-modified#32]
Currently, the moderator events are formatted as:

Time: [##:##:##]
Message: _EventType_
Player name (army): _PlayerName_
Player name (command source): _PlayerName_
Active command Source/Sender: #/#

This takes up a lot of space, repeats info, and shows unnecessary info, which makes it annoying to read through the logs quickly. I would like to suggest to reformat the events as such: [##:##:##] PlayerName EventType. This puts all useful info in one line. Removing the linebreaks between the different items will further condense it still.

**Comment by magge-faf** [comment]
Currently, we have the following events:

        Created a marker with the text
        Created a ping of type
        Self-destructed X units
        Switched focus army from
        Is changing focus army from
        Paused
        Unpaused
        
        
I think everything is useful, except both of the `focus army from`. They get spammed a lot in the chat and their information value is low, until we are sure we can detect malicious behavior from those events. There is too much noise generated from both events, to make any use of it.

I suggest filtering both events out, until it gets polished up.


The output value for the following image is high and works good for moderation workflow:

Are you okay with that text output format?: @IndexLibrorumProhibitorum 

![image](https://github.com/magge-faf/faf-moderator-client-develop-modified/assets/101107758/b3a3969c-335f-4c1b-bf95-2be87b4abb0c)

**Comment by IndexLibrorumProhibitorum** [comment]
Looks good!

**Comment by IndexLibrorumProhibitorum** [comment]
@magge-faf I think this can be closed now?
