### ISSUE TITLE
Show reports with status 'Processing' by default (as part of the 'Awaiting' view)

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [magge-faf/faf-moderator-client-develop-modified#39]
Currently, the 'processing' status is not much used. This is a shame, because it's useful to mark reports that someone is working on. One reason for this is that it's easy to forget that there are reports with this status, because they are filtered out in the default view. 

This can be fixed by including the reports with status processing in the view that's filtered for 'Awaiting'. Alternatively, a new filter option for 'Awaiting + Processing' could be added and made the default view.

**Comment by magge-faf** [comment]
The best solution would be, to make an option in the settingsTab, where you can adjust the filtering and any combination of it to your liking.

The current hard-coded approach is "okay-_ish_", like in the original client, but more customization to fit the Moderators work-flow would not hurt.
