### ISSUE TITLE
Feature request: Add message of "No second accounts found" to smurf village output log when no second accounts found

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [magge-faf/faf-moderator-client-develop-modified#49]
**Proposal:**

Add proof of successful completion of smurf village lookup to output log when no other accounts for the searched ID were found. This would communicate that the check was completed successfully, rather than aborted/crashed mid-check.

**Comment by magge-faf** [comment]
Added in the 3.1 release
