### ISSUE TITLE
Change chatGPT instructions to remove toxicity rating and include better instructions

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [magge-faf/faf-moderator-client-develop-modified#50]
Currently, the instructions for the soft integration of ChatGPT include instructions to provide a toxicity rating. This rating is completely arbitrary and has not been useful for moderating the chatlogs. Having experimented with other instructions, I've had most success with the following:

> AI-Prompt: Gaming Moderator Task
> Reported Chat Log Assessing report from <reporter> against offender <offender>:
> Itemize all instances of speech by the offender. Translate to English where required

Requesting the instructions to be adjusted to the above.

**Comment by magge-faf** [comment]
I had mixed results with the current AI prompt, and with the above prompt as well, and it was not always reliable and had too often check the log manually.

It may be better to have an empty prompt by default on GitHub, and Moderators can use their own adjusted prompt in the ai-prompt-text file.

I can add a setting menu point, like the template-stuff, so Moderators can write their own prompt and use that. (Which currently is already doable, but only the .txt file exists, not the menu point in the settingsTab)

Any thoughts on that approach?

**Comment by IndexLibrorumProhibitorum** [comment]
Sounds good, but as my proposed fix is at least better than what we currently have, consider adding the update and then working on new/improved functions later.
