### ISSUE TITLE
Denoise New Moderator Events - GameResult

### ISSUE THREAD

**Issue by magge-faf** [magge-faf/faf-moderator-client-develop-modified#53]
There are new moderator events about `GameResult`, which get really spammy.

Probably Solutions:

- Make a button that toggles the information on/off
- Tame the information and make it more human-readable
- Make a warning, when something is fishy

**Comment by IndexLibrorumProhibitorum** [comment]
See alternative solution #54

**Comment by magge-faf** [comment]
Fixed in the 3.1 release: Introduced buttons to simply filter the events to any liking.
