### ISSUE TITLE
Denoise New Moderator Events - JsonStats 

### ISSUE THREAD

**Issue by magge-faf** [magge-faf/faf-moderator-client-develop-modified#54]
There are new moderator events about `JsonStats`, which get really spammy.  

Probably Solutions:  

- Make a button that toggles the information on/off 
- Tame the information and make it more human-readable 
- Make a warning, when something is fishy

**Comment by IndexLibrorumProhibitorum** [comment]
Alternative solution: separate those messages from the chatlog and append as a block of logs at the end of the cleaned logs.

**Comment by magge-faf** [comment]
TIL: I have to write 'Fixes' in front of every '#' to auto-close several issues at once, otherwise it just closes the first one.

Fixed in the 3.1 release: Introduced buttons to simply filter the events to any liking.
