### ISSUE TITLE
Feature Request: Automatically Check for Smurfs of Recent Registrations

### ISSUE THREAD

**Issue by magge-faf** [magge-faf/faf-moderator-client-develop-modified#55]
~~Automatically check recent registrations for smurfs of temporary and permanent banned users.~~

Edit: My initial request was misleading for the feature I had in mind. I wanted to automatically check for any smurfs for recent registrations.

e.g.

Basically, it iterates through any number of recent registrations you specify and performs a smurf check, outputting the results as usual.

However, I will create another issue for the watchlist-feature you had in mind later.

![image](https://github.com/user-attachments/assets/8c7a6e32-3c54-43a1-aedb-589714407b2f)

---

**Comment by IndexLibrorumProhibitorum** [comment]
Additionally, a way to either place suspected smurfs on a watchlist to quickly check for those accounts becoming active after periods of inactivity.
