### ISSUE TITLE
Feature request: Add a cancel button to the smurf-check process

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [magge-faf/faf-moderator-client-develop-modified#58]
I'd like to request a cancel button to stop the smurf-check once it has been initiated. Automatic smurf checks sometimes take quite a bit of time, and currently there is no way to stop the processes aside from restarting the mordor client once the process has been started.

**Comment by magge-faf** [comment]
This is definitely needed. I will look into a `pause` and `stop` button. 

Additionally, a check if the session-token is expired, so you do not get spammed by errors when your working session is longer than an hour with Mordor, and you are still in process with smurf-checks. If that should be more complicated, then I will raise an own issue for that.
