### ISSUE TITLE
Feature request/bug: Smurfvillage settings are not saved when Mordor is closed

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [magge-faf/faf-moderator-client-develop-modified#61]
The toggle-able settings that govern which data is used for the smurfvillage process are not being saved for the next time Mordor is launched.

**Comment by magge-faf** [comment]
There is some bug to fix which is on my TODO list since ages, because the save-load implementation was very "asap" back then - will look into it to finally polish it up. Thanks for the reminder.
