### ISSUE TITLE
Bug: Second ID missing in player games comparison results in avalanche of errors

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [magge-faf/faf-moderator-client-develop-modified#72]
Running the new function to check if two ID's have shared games creates a large number of error warning popups if the second ID input field is empty.

![image](https://github.com/user-attachments/assets/6e3a1720-d521-4f90-b14f-c4f867da0a3a)

**Comment by magge-faf** [comment]
I can catch that exception, so no error pops up in the next version - You need to provide two player IDs to make use of that 'Check' method.

**Comment by IndexLibrorumProhibitorum** [comment]
Also happens when both fields are empty, I've noticed :)

Didn't intend to trigger either of the two, but misclicked a button.
